#include "left_hand_approximation/left_hand_approximation.hpp"
#include "right_hand_approximation/right_hand_approximation.hpp"
#include "trapezoidal_approximation/trapezoidal_approximation.hpp"
#include "simpsons_approximation/simpsons_approximation.hpp"
#include "mid_point_approximation/mid_point_approximation.hpp"
#include "approximation/approximation.hpp"