#include "left_hand_approximation.hpp"
#include "right_hand_approximation.hpp"
#include "trapezoidal_approximation.hpp"
#include "simpsons_approximation.hpp"
#include "mid_point_approximation.hpp"
#include "approximation.hpp"